# Site settings
# baseURL = "https://example.org/"
baseURL = ""
languageCode = "nl-be"
title = "Neteworking Lier"
theme = "hugo-big-picture-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
copyright = "&copy; 2019 Fluid-IT"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Header
  [params.header]
    title = '''<a href="index.html"><span class="circuitry"><font size="6" color="#5480f1">net</font></span><span class="cricket"><font size="6" color="#5480f1"><i>e</i></font></span><span class="circuitry"><font size="6" color="#39c088">work</font></span><span class="cricket"><font size="6" color="#39c088"><i>ing</i></font></span></a>
   <font size="2" color="#39454b">&nbsp;by&nbsp;</font>
    <a href="http://www.fluid-it.be/"><span class="fluid"><font size="6" color="#5480f1">fluid</font></span><span class="hexagon"><font size="4" color="#39c088">I</font><font size="4" color="#e44c65">T</font></span></a>
    '''

  # Contact section
  # Form submissions by https://formspree.io/
  [params.contact]
    title = "Say Hello."
    text = "Lorem ipsum dolor sit amet et sapien sed elementum egestas dolore condimentum."
    email = "your@mail.com"
    sendBtnText = "Send Message"
    subject = "New submission from my website!"
    plainText = false

  # Social Icons
  [[params.social]]
    medium = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com"

  [[params.social]]
    medium = "Instagram"
    icon = "fa-instagram"
    link = "https://instagram.com"

  [[params.social]]
    medium = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://linkedin.com"

  [[params.social]]
    medium = "GitHub"
    icon = "fa-github"
    link = "https://github.com"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://html5up.net/license
