# Site settings
baseURL = "https://example.org/"
languageCode = "en-US"
title = "Big Picture by HTML5 UP"
theme = "hugo-big-picture-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
copyright = "&copy; 2017 Adam Jensen"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

  # Header
  [params.header]
    title = "Adam Jensen"

  # Contact section
  # Form submissions by https://formspree.io/
  [params.contact]
    title = "Say Hello."
    text = "Lorem ipsum dolor sit amet et sapien sed elementum egestas dolore condimentum."
    email = "your@mail.com"
    sendBtnText = "Send Message"
    subject = "New submission from my website!"
    plainText = false

  # Social Icons
  [[params.social]]
    medium = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com"

  [[params.social]]
    medium = "Instagram"
    icon = "fa-instagram"
    link = "https://instagram.com"

  [[params.social]]
    medium = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://linkedin.com"

  [[params.social]]
    medium = "GitHub"
    icon = "fa-github"
    link = "https://github.com"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://html5up.net/license
